os: linux
dist: xenial
language: cpp
compiler:
    - gcc
    - clang

branches:
    only: travis-test

before_install:
    - sudo apt-get update

install:
    - build-essential
    - cmake
    - git
    - libgtk2.0-dev
    - pkg-config
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - python-dev
    - python-numpy
    - libtbb2
    - libtbb-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libdc1394-22-dev

before_script:
    - ./install_opencv.sh
    
script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . 
