os: linux
dist: xenial
language: cpp
compiler: gcc

branches:
    only: travis-test

before_install:
    - sudo apt-get update

    
script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . 
